# Site settings
title: Zixuan Liu
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zix.no" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zixuan Liu
user_description: "I'm a software engineer"
user_title: Software Engineer
email: zixuan.liu1@gmail.com
# twitter_username: lorem_ipsum
github_username:  zixliu
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
